[package]
name = "priority_queue_test"
version = "0.1.0"
authors = ["ayamir <lgt986452565@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
